import{a as v,S as P,i as a}from"./assets/vendor-Dx0MPrJo.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const M="30574226-c78049c6609f1ef002c05ad71",q="https://pixabay.com/api/";async function m(o,t=1){const i={key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await v.get(q,{params:i})).data}const h=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".load-more");let E=new P(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:l,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s}">
          <img class="gallery-image" src="${i}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${r}</p>
          <p class="info-item"><b>Views:</b> ${l}</p>
          <p class="info-item"><b>Comments:</b> ${w}</p>
          <p class="info-item"><b>Downloads:</b> ${S}</p>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),E.refresh()}function B(){h.innerHTML=""}function p(){d&&d.classList.remove("hidden")}function y(){d&&d.classList.add("hidden")}function b(){u&&u.classList.remove("hidden")}function f(){u&&u.classList.add("hidden")}const L=document.querySelector(".form"),R=document.querySelector(".load-more");let c="",n=1;L.addEventListener("submit",$);R.addEventListener("click",O);async function $(o){if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),!c){a.warning({title:"Caution",message:"Please enter a search term before submitting!",position:"topRight"});return}n=1,B(),f(),p();try{const t=await m(c,n);if(t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits);const i=Math.ceil(t.totalHits/15);n>=i?a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):b()}catch{a.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{y(),L.reset()}}async function O(){n+=1,f(),p();try{const o=await m(c,n);g(o.hits);const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}const i=Math.ceil(o.totalHits/15);n>=i?(f(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch{a.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight"})}finally{y()}}
//# sourceMappingURL=index.js.map
